# Speaker Level Style
## 2-speaker
python train.py -cpk JointLateClusterSoftStyle4_G -tb 1 -exp 1 -speaker '["corden", "lec_cosmic"]' -model JointLateClusterSoftStyle4_G -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1}' -note mix-stage -save_dir save/mix-stage -modalities '["pose/normalize", "audio/log_mel_400"]' -fs_new '[15, 15]' -input_modalities '["audio/log_mel_400"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 20 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -style_iters 3000 -num_iters 3000 -no_grad 0

## 4-speaker
python train.py -cpk JointLateClusterSoftStyle4_G -tb 1 -exp 1 -speaker '["corden", "lec_cosmic", "ytch_prof", "oliver"]' -model JointLateClusterSoftStyle4_G -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1}' -note mix-stage -save_dir save/mix-stage -modalities '["pose/normalize", "audio/log_mel_400"]' -fs_new '[15, 15]' -input_modalities '["audio/log_mel_400"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 20 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -style_iters 3000 -num_iters 3000 -no_grad 0

## 8-speaker
python train.py -cpk JointLateClusterSoftStyle4_G -tb 1 -exp 1 -speaker '["corden", "lec_cosmic", "ytch_prof", "oliver", "ellen", "noah", "lec_evol", "maher"]' -model JointLateClusterSoftStyle4_G -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1}' -note mix-stage -save_dir save/mix-stage -modalities '["pose/normalize", "audio/log_mel_400"]' -fs_new '[15, 15]' -input_modalities '["audio/log_mel_400"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 20 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -style_iters 3000 -num_iters 3000 -no_grad 0

# Attribute Level Style
## Sit/Stand
python train.py -cpk mix-stage -tb 1 -exp 1 -speaker '["noah", "maher"]' -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1}' -note mix-stage -save_dir save/mix-stage -model JointLateClusterSoftStyle4_G -modalities '["pose/normalize", "audio/log_mel_400"]' -fs_new '[15, 15]' -input_modalities '["audio/log_mel_400"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 20 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -style_iters 3000 -num_iters 3000 -no_grad 0

## Gesture Frequency
python train.py -cpk mix-stage -tb 1 -exp 1 -speaker '["seth", "oliver"]' -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1}' -note mix-stage -save_dir save/mix-stage -model JointLateClusterSoftStyle4_G -modalities '["pose/normalize", "audio/log_mel_400"]' -fs_new '[15, 15]' -input_modalities '["audio/log_mel_400"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 20 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -style_iters 3000 -num_iters 3000 -no_grad 0

## Facing Orientation
python train.py -cpk mix-stage -tb 1 -exp 1 -speaker '["chemistry", "lec_evol"]' -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1}' -note mix-stage -save_dir save/mix-stage -model JointLateClusterSoftStyle4_G -modalities '["pose/normalize", "audio/log_mel_400"]' -fs_new '[15, 15]' -input_modalities '["audio/log_mel_400"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 20 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -style_iters 3000 -num_iters 3000 -no_grad 0

## Dominant Arm
python train.py -cpk mix-stage -tb 1 -exp 1 -speaker '["lec_cosmic|leftarm", "lec_cosmic|rightarm"]' -modelKwargs '{"lambda_id": 0.1, "argmax": 1, "some_grad_flag": 1, "train_only": 1}' -note mix-stage -save_dir save/mix-stage -model JointLateClusterSoftStyle4_G -modalities '["pose/normalize", "audio/log_mel_400"]' -fs_new '[15, 15]' -input_modalities '["audio/log_mel_400"]' -output_modalities '["pose/normalize"]' -gan 1 -loss L1Loss -window_hop 5 -render 0 -batch_size 16 -num_epochs 20 -stop_thresh 3 -overfit 0 -early_stopping 0 -dev_key dev_spatialNorm -num_clusters 8 -feats '["pose", "velocity", "speed"]' -style_iters 3000 -num_iters 3000 -no_grad 0
